[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "HWPt83kCd84ADojQ3naUHDNBScwaYufoTCiJhKPR5MjL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
