[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "7btnX5CoGiEwJBahdGUN1oKQvvpdQVWb5CU3zq9p7Msw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/skydiver/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
