[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "CS6ZR7dbDw2jh3zgegzWYYjRzDSAkDJ55PhJDQXNkcPC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=ad9e5b62-6697-44f4-baf1-ee5d31b9f166"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
