[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "3pw4sNvB8qvq6vwE771MCiyvQ3dboBCJYTfPJe8kUYnM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
