[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "64w7cCF6x8iVp2qD7f1PyeMKT1CTMwwvHUASfjYnbo52"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
